#!/bin/bash
spec_dir=$(cd $(dirname $0); pwd)

echo . /usr/local/rpm-specs/setup_env.fedrepo.sh

if [[ $# -gt 0 ]]
then
  EXTRA="'. /usr/local/rpm-specs/setup_env.fedrepo.sh ${@}'"
else
  EXTRA=bash
fi

eval docker run --cap-add=SYS_ADMIN -it \
  -v "${HOME}/.gitconfig":/usr/local/.gitconfig \
  -v "${HOME}/.ssh":/usr/local/.ssh \
  -v "${spec_dir}":/usr/local/rpm-specs \
  fedora:rawhide \
  bash -c $EXTRA

  # After July 10th, 2017, fedrepo_req shall be used. (?)
  # -v "$(cd $(dirname $0)/../fedrepo_req; pwd)":/usr/local/fedrepo_req \

# vim:et:sw=2:sts=2:ts=2
