#!/bin/bash
rpm_specs_dir=$(cd $(dirname $0); pwd)

echo . /usr/local/rpm-specs/setup_env.review.sh

if [[ $# = 1 ]]
then
  readonly package_name="${1}"
  EXTRA="'. /usr/local/rpm-specs/setup_env.review.sh /usr/local/rpm-specs/${package_name}'"
else
  EXTRA=bash
fi

eval docker run --cap-add=SYS_ADMIN -it \
  -v "${rpm_specs_dir}":/usr/local/rpm-specs \
  -v "$(cd $(dirname $0)/../fedrepo_req; pwd)":/usr/local/fedrepo_req \
  fedora:33 \
  bash -c $EXTRA

  # Both fc25 and rawhide would come with mock 1.4+ which would break inside
  # Docker?!
  # fedora:latest \
  # fedora:rawhide \

# vim:et:sw=2:sts=2:ts=2
