#!/bin/bash
spec_dir=$(cd $(dirname $0); pwd)

echo . /usr/local/rpm-specs/setup_env.review.sh

if [[ $# = 1 ]]
then
  EXTRA="'. /usr/local/rpm-specs/setup_env.review.sh /usr/local/rpm-specs/$1'"
else
  EXTRA=bash
fi

eval docker run --cap-add=SYS_ADMIN -it \
  -v "${spec_dir}":/usr/local/rpm-specs \
  -v "$(cd $(dirname $0)/../fedrepo_req; pwd)":/usr/local/fedrepo_req \
  fedora:24 \
  bash -c $EXTRA

  # Both fc25 and rawhide would come with mock 1.4+ which would break inside
  # Docker?!
  # fedora:latest \
  # fedora:rawhide \

# vim:et:sw=2:sts=2:ts=2
